name: CI Pipeline

on: [push]

jobs:
  style_check:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install black
        run: pip install black

      - name: Run black
        run: black --diff --check .

  test:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov coverage
      - name: Run tests with coverage
        run: |
          pytest --cov=. --cov-report=term --cov-report=xml --cov-config=.coveragerc
      - name: Upload coverage file
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          include-hidden-files: true
          path: .coverage
          retention-days: 1

      - name: Ensure .coverage is ignored
        run: echo '.coverage' >> .gitignore
  
  coverage_report:
    runs-on: ubuntu-24.04
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coverage
      - name: Download coverage artifact
        uses: actions/download-artifact@v4
        with:
          name: coverage-report

      - name: Generate coverage report and XML
        run: |
          coverage report
          coverage xml -o coverage.xml
      - name: Upload coverage XML
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml
          retention-days: 14 